### ISSUE TITLE
Deadlock between clatd.service and network-online.target

### ISSUE THREAD

**Issue by patrakov** [toreanderson/clatd#22]
I have installed clatd on my Arch Linux box. After that, I noticed that `NetworkManager-wait-online.service` started to time out. Without the NetworkManager dispatcher script provided by clatd, `NetworkManager-wait-online.service` does not time out.

I believe (but don't have a good proof yet) this situation is caused by the unit dependencies not being well thought out.

Namely, the NetworkManager dispatcher script calls `systemctl restart clatd`. At the time it is called, NetworkManager may not yet think that the network is online. But without the script finishing, it will not become online.

Proposal: understand that there are two use cases for clatd, and implement two systemd units for both.

First, the current use case: attempt to configure that `clat` interface when the system thinks it is online. For that, we need exactly the current systemd unit, and we don't need the dispatcher script.

Second, the dynamic use case: for that, we do need the dispatcher script, but we don't need the `network-online.target` dependency there. So, it should be a different systemd unit, e.g. `nm-clatd.service`.

**Comment by toreanderson** [comment]
Could you check if substituting `systemctl restart clatd.service` for `systemctl --no-block restart clatd.service` in the NetworkManager dispatcher scripts solves the problem?

**Comment by patrakov** [comment]
Yes, this works.

Still, there are multiple restarts of clatd during boot, and, although I can no longer trigger the "clatd.service: Start request repeated too quickly" error, I thing it would be good to also add this to the service file:

```
[Unit]
StartLimitIntervalSec=0
```
