### ISSUE TITLE
clatd in router mode.

### ISSUE THREAD

**Issue by zod076** [toreanderson/clatd#26]
Hi, currently clatd runs in Host mode, can it work in routed mode on a box with dual NICs ?

I have a 2nd gateway in my LAN for testing purposes and it has 2 NICs. 1st NIC is dual-stack connected to the LAN, 2nd NIC is IPv6-only connected to a Windows laptop and is IPv6-only too.

Also, PLAT is serving the LAN on the 1st NIC.

**Comment by toreanderson** [comment]
Hi, I assume that if you enable forwarding of IPv4 traffic and masquerading/SNAT of forwarded traffic following the IPv4 default route into the  `clat` interface, it should work just fine.
