### ISSUE TITLE
clatd hangs when ufw firewall turned on

### ISSUE THREAD

**Issue by vwidmer** [toreanderson/clatd#28]
Starting clatd v1.6 by Tore Anderson <tore@fud.no>
Performing DNS64-based PLAT prefix discovery (cf. RFC 7050)
Looking up 'ipv4only.arpa' using system resolver
No AAAA records was returned for 'ipv4only.arpa'
No PLAT prefix could be discovered. Your ISP probably doesn't provide NAT64/DNS64 PLAT service. Exiting.

**Comment by toreanderson** [comment]
This output tells me that your DNS server does not provide DNS64 service, thus clatd cannot discover your ISP's NAT64 prefix.

You can confirm this with `getent ahosts ipv4only.arpa` - if it does not return any IPv6 addresses, there is no DNS64 service.

I doubt this has anything to do with firewalling.
