### ISSUE TITLE
perl install script for necessary modules

### ISSUE THREAD

**Issue by christianhenschel** [toreanderson/clatd#33]
Unfortunately I had to install the perl moduels manually after clatd installation.
I've created a script to resolve that issue:
#!/bin/bash
export PERL_MM_USE_DEFAULT=1
perl -MCPAN -e 'install Net::IP'
perl -MCPAN -e 'install IO::Socket::INET6'
perl -MCPAN -e 'install Net::DNS'
perl -MCPAN -e 'reload cpan'

Like I've documented previously in the past:
https://henschel.network/nat464xlat-with-clatd-on-ubuntu-18-04-lts/

I've seen this on Debian and Ubuntu.

**Comment by toreanderson** [comment]
I'm confused - did you get an error message from `make installdeps`? If so, what was it?
