### ISSUE TITLE
doesn't work without systemd

### ISSUE THREAD

**Issue by shithubsucks** [toreanderson/clatd#40]
This software assumes systemd and doesn't work without it. 

I've managed to get it running by manually coping the files into if-down.d and if-up.d, setting up /etc/default/clatd,  and then in a root interactive terminal manually invoking clatd. This seems to start the tun interface just fine.

Why is systemd a dependency to make this work? I don't see how that is actually needed here.

**Comment by toreanderson** [comment]
clatd contains, to the best of my recollection, exactly zero dependencies on systemd. What makes you believe otherwise?

**Comment by toreanderson** [comment]
> the debian networking ifup/down script clatd.ifupdown relies on systemctl to work

Well, yes, considering that Debian is a distro that uses systemd that is hardly unexpected.

In any case, the script in question - [clatd.ifupdown](https://github.com/toreanderson/clatd/blob/3ea303b5210bf701df30323933c86f9ffe4d3dd4/scripts/clatd.ifupdown) - is mean as an example on how an integration with ifupdown might look like. It is not part of clatd proper, nor is it installed by default.

I am therefore closing this issue. Feel free to submit a PR with improvements to the example ifupdown script, if you have any suggestions on how to make it better.
