### ISSUE TITLE
Needs to work on Mac OS X

### ISSUE THREAD

**Issue by davidsummers** [toreanderson/clatd#5]
This works great on Linux!

Does anyone have any ideas on getting this to work on Mac OS X?

I started to take a look at it and it makes it up to the "ip" command and since Mac OS X doesn't have that, it fails at that point.

I suspect with some way to determine platform and a bit of re-working which commands are called and how they are parsed, the MAC OS X platform could be supported.

Thoughts?

**Comment by davidsummers** [comment]
Oh, I forgot, this depends on Tayga.  

Is it possible to have NAT64 translation on Mac OS X or port tayga to MAC OS X?

**Comment by thomasschaeferm** [comment]
Mac OS X has some built in NAT64-capabilities

https://developer.apple.com/library/ios/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html#//apple_ref/doc/uid/TP40010220-CH213-SW1

but its purpose is only testing IOS-Apps.

Apple don’t' want to use clat, it expects that APPs are IPv6-native or compatible with NAT64.

**Comment by davidsummers** [comment]
Yes, that is what I suspected.

Is there any way to use the built-in NAT64 to make this work?

If not, is there a way to do it with TAYGA?

I'm on an IPv6-only network and have web pages that don't load because of IPv4 literals, so would really be great to be able to figure out a way to do this on OS X.

I'm currently playing with MAC OS HomeBrew installer to install MAC OS X tuntap and then I've got a slightly hacked version of tayga that now compiles but doesn't yet work and I'm investigating how to get it to work.

If anyone has something that works, please let me know.

**Comment by toreanderson** [comment]
This would certainly be a nice feature to have, but as I don't own any Apple devices there's just no way I can implement this on my own. Truth to be told I have no idea if it is even possible. So I'm going to close this issue as «wontfix». That said, if anyone else is able to make it work I'd of course welcome a pull request.
